import { afterEach, describe, expect, test } from "bun:test";
import { AgentClient, DeterministicSyncHub, ProtocolServer } from "../../src/index.ts";
import { closeAll, makeRoot, openReplica, seedBoth, type Replica } from "./helpers.ts";
let root:string;let a:Replica|undefined,b:Replica|undefined;
afterEach(async()=>{if(root)await closeAll(root,a,b);a=b=undefined;});
describe("Slice 4 restart, interval, manifests, and protocol",()=>{
 test("persists device identity, monotonic origin metadata, receipts, and status across restart",async()=>{root=await makeRoot();const hub=new DeterministicSyncHub();a=await openReplica(root,"a",hub);const session=await a.supervisor.createSession({workspaceId:"workspace"});const firstDevice=a.supervisor.device.deviceId;await a.supervisor.appendMessage(session.sessionId,session.branchId,"user","one");await a.supervisor.sync.sync();const before=await a.supervisor.storage.loadEvents(session.sessionId);await a.supervisor.close();a=await openReplica(root,"a",hub);expect(a.supervisor.device.deviceId).toBe(firstDevice);const cycle=await a.supervisor.sync.sync();expect(cycle.ingested).toBe(0);await a.supervisor.appendMessage(session.sessionId,session.branchId,"user","two");const after=await a.supervisor.storage.loadEvents(session.sessionId);expect(after.at(-1)!.originSequence).toBeGreaterThan(Math.max(...before.map(x=>x.originSequence)));expect((await a.supervisor.sync.status()).replica.lastSuccessAt).not.toBeNull();});
 test("materializes only allowlisted model-facing preferences and excludes routing records",async()=>{root=await makeRoot();const hub=new DeterministicSyncHub();a=await openReplica(root,"a",hub);const session=await a.supervisor.createSession({workspaceId:"workspace"});await a.supervisor.profile.setPreference("response.style",{concise:true});await a.supervisor.profile.setPreference("recent.session.other-workspace","unrelated-session");await a.supervisor.profile.installGlobalSkill({skillId:"global:review",name:"review",definition:{runtime:"bun",source:"export default () => 'ok'"}});await a.supervisor.profile.putCredentialReference({reference:"provider:main",provider:"example",label:"Main provider",metadata:{region:"local"}});const materialized=await a.supervisor.contexts.materialize(session.sessionId,session.branchId);expect((materialized.context as any).userProfile.preferences.map((item:any)=>item.key)).toEqual(["response.style"]);expect((materialized.context as any).userProfile.globalSkills).toEqual([]);expect((await a.supervisor.skillManagement.list(session.sessionId,session.branchId,{includeUnavailable:true})).find(item=>item.entryId==="global:review")).toMatchObject({legacy:true,availability:"disabled"});expect((materialized.context as any).userProfile).not.toHaveProperty("providerConfigurations");expect(JSON.stringify(materialized.context)).not.toContain("unrelated-session");expect(JSON.stringify(materialized.context)).not.toContain("provider:main");expect((materialized.context as any).agentProfile.role).toBe("Repository agent");expect(JSON.stringify(materialized.context)).not.toContain("authToken");});
  test("runs configured interval synchronization without making it durable session identity",async()=>{root=await makeRoot();const hub=new DeterministicSyncHub();a=await openReplica(root,"a",hub,{intervalMs:10});b=await openReplica(root,"b",hub);const session=await a.supervisor.createSession({workspaceId:"workspace"});for(let i=0;i<20;i++){await Bun.sleep(10);await b.supervisor.sync.sync();if(await b.supervisor.storage.getSession?.(session.sessionId))break;}expect(await b.supervisor.storage.getSession?.(session.sessionId)).not.toBeNull();});
 test("produces ownership-aware resource and replica manifests without claiming unsupported cloud deletion",async()=>{root=await makeRoot();const hub=new DeterministicSyncHub();a=await openReplica(root,"a",hub);const session=await a.supervisor.createSession({workspaceId:"workspace"});const artifact=await a.supervisor.artifacts.put("owned export",{mediaType:"text/plain"});await a.supervisor.storage.appendEvents([{sessionId:session.sessionId,branchId:session.branchId,type:"ArtifactRegistered",producer:"supervisor",idempotencyKey:"export-artifact",payload:artifact}]);const exported=await a.supervisor.sync.exportBundle(`${a.directory}/exported`,"session",session.sessionId,"owner");expect(exported.owned).toBe(true);expect(exported.status).toBe("completed");expect((exported.resources as any).artifactDirectory).toContain("artifacts");expect(await Bun.file(`${a.directory}/exported/events.jsonl`).text()).toContain("ArtifactRegistered");expect(await Bun.file(`${a.directory}/exported/artifacts/${artifact.digest}`).text()).toBe("owned export");const deletion=await a.supervisor.sync.createManifest("delete","workspace","workspace","owner");expect(deletion.status).toBe("blocked");expect((deletion.resources as any).remoteDeletionSupported).toBe(false);const foreign=await a.supervisor.sync.createManifest("export","session","not-owned","owner");expect(foreign.owned).toBe(false);expect(foreign.status).toBe("blocked");});
 test("exposes sync status, manual sync, discovery, manifests, and truthful bidirectional-test-hub push failure over AgentClient",async()=>{root=await makeRoot();const hub=new DeterministicSyncHub();a=await openReplica(root,"a",hub);const protocol=new ProtocolServer(a.supervisor);const server=protocol.listen();const client=new AgentClient(`http://${server.hostname}:${server.port}`);try{const status=await client.syncStatus();expect(status.capabilities.networkSync).toBe(true);expect(status.capabilities.directionalNetworkPush).toBe(false);expect((await client.syncNow()).status.lifecycle).toBe("online");expect((await client.cloudWorkspaces()).map(x=>x.workspaceId)).toEqual(["workspace"]);const manifest=await client.dataManifest("export","workspace","workspace","owner");expect(manifest.owned).toBe(true);await expect(client.syncPush()).rejects.toThrow("CAPABILITY_UNAVAILABLE");}finally{protocol.stop();}});
});
