import { afterEach, describe, expect, test } from "bun:test";
import { CapabilityUnavailableError, DeterministicSyncHub } from "../../src/index.ts";
import { closeAll, makeRoot, openReplica, seedBoth, type Replica } from "./helpers.ts";
let root:string;let a:Replica|undefined,b:Replica|undefined;
afterEach(async()=>{if(root)await closeAll(root,a,b);a=b=undefined;});
describe("Slice 4 offline-first synchronization lifecycle",()=>{
 test("keeps working offline, reports failure honestly, and catches up on reconnect",async()=>{root=await makeRoot();const hub=new DeterministicSyncHub();a=await openReplica(root,"a",hub);b=await openReplica(root,"b",hub);const session=await seedBoth(a,b);b.transport.setOnline(false);await b.supervisor.appendMessage(session.sessionId,session.branchId,"user","offline B");await expect(b.supervisor.sync.sync()).rejects.toThrow("offline");const failed=await b.supervisor.sync.status();expect(failed.replica.lifecycle).toBe("error");expect(failed.replica.lastSuccessAt).not.toBeNull();expect(failed.replica.lastError).toContain("offline");expect((await b.supervisor.storage.loadEvents(session.sessionId,{branchId:session.branchId})).some(e=>(e.payload as any).content==="offline B")).toBe(true);b.transport.setOnline(true);await b.supervisor.sync.reconnect();await a.supervisor.sync.sync();expect((await a.supervisor.storage.loadEvents(session.sessionId)).some(e=>(e.payload as any).content==="offline B")).toBe(true);});
 test("preserves concurrent offline advancement as derived branches without losing either writer",async()=>{root=await makeRoot();const hub=new DeterministicSyncHub();a=await openReplica(root,"a",hub);b=await openReplica(root,"b",hub);const session=await seedBoth(a,b);await a.supervisor.appendMessage(session.sessionId,session.branchId,"user","from A");await b.supervisor.appendMessage(session.sessionId,session.branchId,"user","from B");await a.supervisor.sync.sync();await b.supervisor.sync.sync();await a.supervisor.sync.sync();const branches=await a.supervisor.storage.listBranches();expect(branches.length).toBe(2);const histories=await Promise.all(branches.map(x=>a!.supervisor.storage.loadEvents(x.sessionId,{branchId:x.branchId})));const texts=histories.flatMap(events=>events.filter(e=>e.type==="MessageAppended").map(e=>(e.payload as any).content));expect(new Set(texts)).toEqual(new Set(["from A","from B"]));expect(histories.some(events=>events.some(e=>e.type==="BranchCreated"&&e.producer==="sync-derived"))).toBe(true);expect((await a.supervisor.sync.conflicts("unresolved")).some(x=>x.kind==="divergent_session")).toBe(true);});
 test("does not turn a remote owner's effect request into locally executable outbox work",async()=>{root=await makeRoot();const hub=new DeterministicSyncHub();a=await openReplica(root,"a",hub);b=await openReplica(root,"b",hub);const session=await seedBoth(a,b);const effectId=await a.supervisor.outbox.request({sessionId:session.sessionId,branchId:session.branchId,executor:"shell",operation:"run",input:{command:"printf owner-only"},idempotencyKey:"owner-only-effect",idempotent:true});await a.supervisor.sync.sync();await b.supervisor.sync.sync();expect((await b.supervisor.storage.loadEvents(session.sessionId)).some(e=>e.type==="EffectRequested"&&(e.payload as any).effectId===effectId)).toBe(true);expect(await b.supervisor.storage.getOutbox(effectId)).toBeNull();expect((await b.supervisor.storage.getSession?.(session.sessionId))?.executionOwnerDeviceId).toBe(a.supervisor.device.deviceId);await expect(b.supervisor.modelLoop.turn(session.sessionId,session.branchId)).rejects.toMatchObject({code:"CAPABILITY_UNAVAILABLE"});});
  test("keeps the bidirectional-only in-process hub honest about unsupported directional calls",async()=>{root=await makeRoot();const hub=new DeterministicSyncHub();a=await openReplica(root,"a",hub);await a.supervisor.createSession({workspaceId:"workspace"});expect(await a.supervisor.sync.stage()).toBe(1);expect((await a.supervisor.sync.status()).capabilities.directionalNetworkPush).toBe(false);await expect(a.supervisor.sync.push()).rejects.toBeInstanceOf(CapabilityUnavailableError);await expect(a.supervisor.sync.pull()).rejects.toBeInstanceOf(CapabilityUnavailableError);});
 test("discovers cloud workspaces from replicated announcements",async()=>{root=await makeRoot();const hub=new DeterministicSyncHub();a=await openReplica(root,"a",hub);b=await openReplica(root,"b",hub);await a.supervisor.sync.sync();await b.supervisor.sync.sync();const discovered=await b.supervisor.sync.discoverCloudWorkspaces();expect(discovered).toHaveLength(1);expect(discovered[0]?.workspaceId).toBe("workspace");expect(discovered[0]?.name).toBe("Shared workspace");});
});
