import { existsSync } from "node:fs";
import { resolve } from "node:path";

const root=resolve(import.meta.dir,"..");const read=(path:string)=>Bun.file(resolve(root,path)).text();const failures:string[]=[];
const require=(condition:boolean,message:string)=>{if(!condition)failures.push(message);};

const prd=await read("2026-08-05-prime-agent-typescript-turso-rewrite-prd.md");const acceptance=prd.split("## Acceptance criteria")[1]?.split("## References")[0]??"";const criteria=acceptance.split("\n").filter(line=>line.startsWith("- "));require(criteria.length===18,`PRD acceptance list changed: expected 18 bullets, found ${criteria.length}`);
const matrix=await read("docs/full-system-acceptance.md");const ids=[...matrix.matchAll(/^\| (AC-\d{2}) \|/gm)].map(match=>match[1]!);require(ids.length===18,`acceptance matrix must have 18 rows, found ${ids.length}`);require(new Set(ids).size===18,"acceptance matrix IDs must be unique");for(let index=1;index<=18;index++)require(ids[index-1]===`AC-${String(index).padStart(2,"0")}`,`acceptance matrix is missing or reorders AC-${String(index).padStart(2,"0")}`);
for(const match of matrix.matchAll(/`((?:test|scripts|docs)\/[^`]+?\.(?:ts|md))`/g))require(existsSync(resolve(root,match[1]!)),`matrix references missing evidence file ${match[1]}`);
for(const command of ["bun run verify","TURSO_SYNC_SERVER_BIN","bun run test:turso-official","bun run check:architecture"])require(matrix.includes(command),`matrix omits reproducible command/evidence ${command}`);

const packageJson=JSON.parse(await read("package.json"));require(packageJson.dependencies?.["@tursodatabase/sync"]==="0.7.2","official Turso Sync dependency must be exactly pinned to 0.7.2");require(String(packageJson.scripts?.verify).includes("check:acceptance"),"verify must execute the acceptance-matrix check");require(String(packageJson.scripts?.["test:turso-official"]).includes("official-server-conformance"),"official server command must run the credential-free harness");
const official=await read("test/slice4/official-server-conformance.test.ts");for(const marker of ["TURSO_SYNC_SERVER_BIN","test.skipIf(!binary)","Turso 0.7.2","--sync-server","TursoSyncTransport","Promise.all","task_claim","networkSentBytes","stopProcess","rm(directory"])require(official.includes(marker),`official sync-server harness is missing invariant ${marker}`);

const service=await read("src/sync/service.ts"),contract=await read("src/storage/contract.ts"),libsql=await read("src/storage/libsql.ts"),outbox=await read("src/runtime/outbox.ts");for(const marker of ["DELETE ${input.scopeKind} ${input.scopeId}","ManagedReplicaDeletionAdmin","authenticatedAdministration","artifactDirectoryOwnership","external receipt directory","retainedSharedArtifacts","listReplicaStatuses","managedSyncUrls","unaddressableManagedReplicas","removeTreeAndRecord","TURSO_SYNC_SUFFIXES","main-db","delete-owned-data"])require(service.includes(marker),`physical data control is missing invariant ${marker}`);for(const marker of ["assertIndependentSessionErasable","eraseIndependentSession","CapabilityUnavailableError","DROP TRIGGER events_no_delete","CREATE TRIGGER events_no_delete BEFORE DELETE ON events","retained_event_links","retained_quarantine_links","DELETE FROM sync_quarantine","DELETE FROM events WHERE session_id=?"])require(libsql.includes(marker),`session erasure is missing audited invariant ${marker}`);for(const marker of ["listReplicaStatuses(workspaceId","assertIndependentSessionErasable?:","eraseIndependentSession?:"])require(contract.includes(marker),`destructive administration contract is missing invariant ${marker}`);for(const marker of ["quiesceForDeletion","#claimAdmissions","deletionQuiesced"])require(outbox.includes(marker),`outbox deletion quiescence is missing invariant ${marker}`);
const protocol=await read("src/protocol/client.ts"),server=await read("src/protocol/server.ts"),supervisor=await read("src/runtime/supervisor.ts"),tui=await read("src/tui/index.ts");require(protocol.includes("deleteOwnedData(input" )&&server.includes('parts[1] === "delete"')&&supervisor.includes("async deleteOwnedData"),"typed SDK, HTTP protocol, and supervisor must expose the same explicit deletion operation");require(tui.includes('/resume [branch] /compact')&&tui.includes('event.type==="ModelOutputChunk"'),"TUI must expose resume/compact and consume committed model-output records");require(supervisor.includes("async compact")&&supervisor.includes('kind:"compaction"'),"compaction must be a durable source-linked derivation");require(supervisor.includes("async resume")&&matrix.includes("test/integration/full-system-surfaces.test.ts")&&protocol.includes("compact(sessionId")&&server.includes('parts[2] === "compact"')&&server.includes('parts[2] === "resume"'),"resume/compaction require typed protocol routes and runtime coverage");

if(failures.length){console.error(`Full-system acceptance check failed (${failures.length}):\n${failures.map(item=>`- ${item}`).join("\n")}`);process.exit(1);}console.log(`Full-system acceptance check passed: ${criteria.length} PRD criteria, ${ids.length} evidence rows, official-server and physical-data-control invariants present.`);
