import{afterEach,describe,expect,test}from"bun:test";import{type HarnessContent,type Supervisor,ValidationError}from"../../src/index.ts";import type{TempRuntime}from"../helpers.ts";import{closeSlice3,evidence,openSlice3}from"./helpers.ts";
let current:{supervisor:Supervisor;temp:TempRuntime}|undefined;afterEach(async()=>{if(current)await closeSlice3(current);current=undefined;});
async function promote(s:Supervisor,sessionId:string,branchId:string,kind:"skill"|"subagent_spec",name:string,content:HarnessContent,evidenceId:string){let p=await s.harness.propose(sessionId,branchId,{trigger:"Reusable success",predictedEffect:"Reuse verified behavior",evidenceEventIds:[evidenceId],evaluation:{kind:"objective",name:"verification",metric:"pass",target:true},edits:[{operation:"create",kind,scope:"local",name,content}]});p=await s.harness.validate(sessionId,branchId,p.proposalId);p=await s.harness.activate(sessionId,branchId,p.proposalId);const a=await s.harness.allocate(sessionId,branchId,p.proposalId);await s.contexts.materialize(sessionId,branchId);await s.harness.recordObservation(sessionId,branchId,p.proposalId,{allocationId:a.allocationId,evaluator:"test",objective:false,success:true,metric:true,evidenceEventIds:[evidenceId]});await s.harness.decide(sessionId,branchId,p.proposalId);return (await s.harness.list({kind})).find(x=>x.name===name)!;}
describe("Slice 3 generated TypeScript skills and subagent specifications",()=>{
 test("compile/runtime tests and exact-version invocation execute only through durable effects",async()=>{current=await openSlice3();const s=current.supervisor;const x=await s.createSession({workspaceId:"w"});const ev=await evidence(s,x.sessionId,x.branchId);const entry=await promote(s,x.sessionId,x.branchId,"skill","double",{kind:"skill",description:"Double n",source:"export default (input:{n:number}) => ({n:input.n*2});",inputSchema:{type:"object",required:["n"]},permissions:[],runtime:"bun",tests:[{name:"two",input:{n:2},expected:{n:4}}]},ev.id);const invoked=await s.skills.invoke(x.sessionId,x.branchId,entry.entryId,{n:3},{versionId:entry.current.versionId,idempotencyKey:"invoke-double"});expect(invoked.outcome).toBe("succeeded");expect((invoked.output as any).value).toEqual({n:6});const events=await s.storage.loadEvents(x.sessionId,{branchId:x.branchId});const request=events.find(e=>e.type==="EffectRequested"&&(e.payload as any).effectId===invoked.effectId)!;expect((request.payload as any).executor).toBe("skill");expect((request.payload as any).input.versionId).toBe(entry.current.versionId);expect(events.some(e=>e.type==="SkillTestRecorded"&&(e.payload as any).versionId===entry.current.versionId)).toBe(true);expect(events.some(e=>e.type==="SkillInvocationRecorded"&&(e.payload as any).versionId===entry.current.versionId)).toBe(true);expect(s.skills.invoke(x.sessionId,x.branchId,entry.entryId,{missing:1})).rejects.toBeInstanceOf(ValidationError);
 });
 test("rejects generated skill activation when compilation or runtime tests fail",async()=>{current=await openSlice3();const s=current.supervisor;const x=await s.createSession({workspaceId:"w"});const ev=await evidence(s,x.sessionId,x.branchId);let p=await s.harness.propose(x.sessionId,x.branchId,{trigger:"Bad generation",predictedEffect:"none",evidenceEventIds:[ev.id],evaluation:{kind:"objective",name:"tests",metric:"pass",target:true},edits:[{operation:"create",kind:"skill",scope:"local",name:"broken",content:{kind:"skill",description:"broken",source:"export default ( =>",permissions:[],runtime:"bun",tests:[{name:"runtime",input:null,expected:null}]}}]});p=await s.harness.validate(x.sessionId,x.branchId,p.proposalId);expect(s.harness.activate(x.sessionId,x.branchId,p.proposalId)).rejects.toThrow("compile/runtime tests");const broken=(await s.harness.list({kind:"skill"})).find(x=>x.name==="broken")!;expect(broken.current.status).toBe("rejected");const events=await s.storage.loadEvents(x.sessionId,{branchId:x.branchId});expect(events.some(e=>e.type==="EffectOutcomeRecorded"&&(e.payload as any).outcome==="failed")).toBe(true);
 });
 test("pins a reusable subagent specification version to the normal durable task/session admission",async()=>{current=await openSlice3();const s=current.supervisor;const x=await s.createSession({workspaceId:"w"});const ev=await evidence(s,x.sessionId,x.branchId);const entry=await promote(s,x.sessionId,x.branchId,"subagent_spec","reviewer",{kind:"subagent_spec",role:"reviewer",invocationCriteria:"when a patch exists",expectedArtifact:"review report",prompt:"Review correctness",completionCriteria:"report delivered"},ev.id);const child=await s.specs.spawn(x.sessionId,x.branchId,entry.entryId,{versionId:entry.current.versionId,task:"Review change A",idempotencyKey:"review-a"});expect(child.specVersionId).toBe(entry.current.versionId);const task=await s.storage.getTask?.(child.taskId);expect(task?.task).toContain("Role: reviewer");const rows=await s.storage.readonlyQuery({sql:"SELECT * FROM subagent_spec_invocations WHERE task_id=?",args:[child.taskId]});expect((rows[0] as any).version_id).toBe(entry.current.versionId);expect((await s.specs.spawn(x.sessionId,x.branchId,entry.entryId,{versionId:entry.current.versionId,task:"Review change A",idempotencyKey:"review-a"})).taskId).toBe(child.taskId);
 });
 test("rebuilds every harness, evaluation, skill, and specification projection from canonical events",async()=>{current=await openSlice3();const s=current.supervisor;const x=await s.createSession({workspaceId:"w"});const ev=await evidence(s,x.sessionId,x.branchId);const entry=await promote(s,x.sessionId,x.branchId,"subagent_spec","planner",{kind:"subagent_spec",role:"planner",invocationCriteria:"planning",expectedArtifact:"plan",prompt:"Plan"},ev.id);await s.specs.spawn(x.sessionId,x.branchId,entry.entryId,{idempotencyKey:"plan"});await s.storage.rebuildOperationalProjections?.();const restored=await s.harness.get(entry.entryId);expect(restored?.current.versionId).toBe(entry.current.versionId);const invocations=await s.storage.readonlyQuery({sql:"SELECT version_id FROM subagent_spec_invocations",args:[]});expect((invocations[0] as any).version_id).toBe(entry.current.versionId);
 });
});
