import { afterEach, describe, expect, test } from "bun:test";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { AgentClient, ProtocolServer, Supervisor } from "../../src/index.ts";
import { makeTempRuntime, removeTempRuntime, type TempRuntime } from "../helpers.ts";

let current:{supervisor:Supervisor;temp:TempRuntime}|undefined;
afterEach(async()=>{if(current){await current.supervisor.close();await removeTempRuntime(current.temp);}current=undefined;});
async function open(){const temp=await makeTempRuntime("agencity-skill-management-");const supervisor=await Supervisor.open({databaseUrl:temp.databaseUrl,artifactDirectory:temp.artifactDirectory,workspaceRoot:temp.workspaceRoot,recover:false});current={supervisor,temp};return current;}
async function bundle(temp:TempRuntime,name="triple-number"){const directory=join(temp.directory,name);await mkdir(directory);const manifest={schemaVersion:1,name,description:"Triples one number",entry:"skill.ts",runtime:"bun",inputSchema:{type:"object",properties:{value:{type:"number"}},required:["value"],additionalProperties:false},permissions:[],tests:[{name:"triples",input:{value:2},expected:{value:6}}]};await writeFile(join(directory,"agencity-skill.json"),JSON.stringify(manifest));await writeFile(join(directory,"skill.ts"),"export default (input:{value:number}) => ({value: input.value * 3});\n");return directory;}

describe("FU-017 unified skill management",()=>{
 test("profile install is crash/retry stable and supports repeated raced availability cycles in context and invocation",async()=>{
  const {supervisor:s,temp}=await open();const session=await s.createSession({workspaceId:"w"});const directory=await bundle(temp);const preview=await s.skillManagement.previewImport(directory);
  expect(preview.bundle.warning).toMatchObject({trustModel:"trusted-local",requiresExplicitConfirmation:true});await expect(s.skillManagement.installLocal(session.sessionId,session.branchId,{directory,scope:"profile",confirmationDigest:"0".repeat(64)})).rejects.toThrow(/confirmation/);
  const installInput={directory,scope:"profile" as const,confirmationDigest:preview.confirmationDigest,installedBy:"test-owner"};const installed=await s.skillManagement.installLocal(session.sessionId,session.branchId,installInput);const retries=await Promise.all([s.skillManagement.installLocal(session.sessionId,session.branchId,installInput),s.skillManagement.installLocal(session.sessionId,session.branchId,installInput)]);expect(retries).toEqual([installed,installed]);
  expect(installed).toMatchObject({name:"triple-number",scope:"global",source:"profile",availability:"enabled",legacy:false});expect(installed.provenance).toMatchObject({origin:{kind:"local-directory",reference:preview.bundle.provenance.directory,manifestDigest:preview.bundle.provenance.manifest.sha256,sourceDigest:preview.confirmationDigest}});expect((await s.profile.getGlobalSkillHistory(installed.entryId))?.actions).toHaveLength(1);
  expect(await s.skills.invoke(session.sessionId,session.branchId,"triple-number",{value:4})).toMatchObject({outcome:"succeeded",output:{compiled:true,value:{value:12}}});const cell=await s.executeCell(session.sessionId,session.branchId,`const listed=await sdk.skills.list(); const got=await sdk.skills.get("triple-number"); const invoked=await sdk.skills.invoke("triple-number",{value:5}); return {listed,got,invoked};`);expect(cell.result as any).toMatchObject({got:{name:"triple-number"},invoked:{outcome:"succeeded",output:{value:{value:15}}}});
  const contextHas=async()=>((await s.contexts.materialize(session.sessionId,session.branchId)).context as any).harness.skills.some((item:any)=>item.name==="triple-number");expect(await contextHas()).toBe(true);
  const disabled=await Promise.all([s.skillManagement.disable(session.sessionId,session.branchId,"triple-number"),s.skillManagement.disable(session.sessionId,session.branchId,"triple-number")]);expect(disabled.map(item=>item.availability)).toEqual(["disabled","disabled"]);expect((await s.profile.getGlobalSkill(installed.entryId,{includeUnavailable:true}))?.availability).toBe("disabled");expect(await contextHas()).toBe(false);await expect(s.skills.invoke(session.sessionId,session.branchId,"triple-number",{value:1})).rejects.toMatchObject({code:"NOT_FOUND"});
  const enabled=await Promise.all([s.skillManagement.enable(session.sessionId,session.branchId,"triple-number"),s.skillManagement.enable(session.sessionId,session.branchId,"triple-number")]);expect(enabled.map(item=>item.availability)).toEqual(["enabled","enabled"]);expect(await contextHas()).toBe(true);expect(await s.skills.invoke(session.sessionId,session.branchId,"triple-number",{value:2})).toMatchObject({outcome:"succeeded",output:{value:{value:6}}});
  expect((await s.skillManagement.disable(session.sessionId,session.branchId,"triple-number")).availability).toBe("disabled");expect((await s.profile.getGlobalSkill(installed.entryId,{includeUnavailable:true}))?.availability).toBe("disabled");expect(await contextHas()).toBe(false);
  expect((await s.skillManagement.enable(session.sessionId,session.branchId,"triple-number")).availability).toBe("enabled");expect(await s.skills.invoke(session.sessionId,session.branchId,"triple-number",{value:3})).toMatchObject({outcome:"succeeded",output:{value:{value:9}}});
  expect((await s.skillManagement.remove(session.sessionId,session.branchId,"triple-number")).availability).toBe("removed");await expect(s.skillManagement.enable(session.sessionId,session.branchId,"triple-number")).rejects.toThrow(/Removed/);const history=await s.profile.getGlobalSkillHistory(installed.entryId);expect(history?.versions).toHaveLength(1);expect(history?.actions.map(action=>action.availability)).toEqual(["enabled","disabled","enabled","disabled","enabled","removed"]);expect(new Set(history!.actions.map(action=>action.idempotencyKey)).size).toBe(history!.actions.length);
 });

 test("workspace install resumes one governed lifecycle and repeated raced availability uses canonical sequence",async()=>{
  const {supervisor:s,temp}=await open();const session=await s.createSession({workspaceId:"w"});const directory=await bundle(temp,"workspace-triple");const preview=await s.skillManagement.previewImport(directory);const installInput={directory,scope:"workspace" as const,confirmationDigest:preview.confirmationDigest};const installed=await s.skillManagement.installLocal(session.sessionId,session.branchId,installInput);const retries=await Promise.all([s.skillManagement.installLocal(session.sessionId,session.branchId,installInput),s.skillManagement.installLocal(session.sessionId,session.branchId,installInput)]);expect(retries).toEqual([installed,installed]);
  expect(installed).toMatchObject({source:"harness",scope:"workspace",availability:"enabled",provenance:{installation:{origin:{kind:"local-directory",manifestDigest:preview.bundle.provenance.manifest.sha256,sourceDigest:preview.confirmationDigest}}}});const tests=await s.storage.readonlyQuery({sql:"SELECT execution_kind,passed FROM skill_executions WHERE version_id=? ORDER BY created_at,event_id",args:[installed.versionId]});expect(tests.length).toBeGreaterThanOrEqual(3);expect(tests.every((row:any)=>Number(row.passed)===1)).toBe(true);expect((await s.storage.readonlyQuery({sql:"SELECT observation_id FROM refinement_observations WHERE proposal_id=(SELECT proposal_id FROM harness_versions WHERE version_id=?)",args:[installed.versionId]}))).toHaveLength(2);expect((await s.storage.readonlyQuery({sql:"SELECT id FROM events WHERE type='SkillImported' AND json_extract(payload_json,'$.versionId')=?",args:[installed.versionId]}))).toHaveLength(1);
  const contextHas=async()=>((await s.contexts.materialize(session.sessionId,session.branchId)).context as any).harness.skills.some((item:any)=>item.name===installed.name);expect(await contextHas()).toBe(true);
  const disabled=await Promise.all([s.skillManagement.disable(session.sessionId,session.branchId,installed.entryId),s.skillManagement.disable(session.sessionId,session.branchId,installed.entryId)]);expect(disabled.map(item=>item.availability)).toEqual(["disabled","disabled"]);expect((await s.skillManagement.get(session.sessionId,session.branchId,installed.entryId)).availability).toBe("disabled");expect(await contextHas()).toBe(false);await expect(s.skills.invoke(session.sessionId,session.branchId,installed.name,{value:2})).rejects.toMatchObject({code:"NOT_FOUND"});
  const enabled=await Promise.all([s.skillManagement.enable(session.sessionId,session.branchId,installed.entryId),s.skillManagement.enable(session.sessionId,session.branchId,installed.entryId)]);expect(enabled.map(item=>item.availability)).toEqual(["enabled","enabled"]);expect(await contextHas()).toBe(true);expect(await s.skills.invoke(session.sessionId,session.branchId,installed.name,{value:2})).toMatchObject({outcome:"succeeded",output:{value:{value:6}}});
  await s.skillManagement.disable(session.sessionId,session.branchId,installed.entryId);await s.storage.rebuildOperationalProjections!();expect((await s.skillManagement.get(session.sessionId,session.branchId,installed.entryId)).availability).toBe("disabled");expect(await contextHas()).toBe(false);expect((await s.skillManagement.enable(session.sessionId,session.branchId,installed.entryId)).availability).toBe("enabled");expect(await s.skills.invoke(session.sessionId,session.branchId,installed.name,{value:3})).toMatchObject({outcome:"succeeded",output:{value:{value:9}}});
  const actions=await s.storage.readonlyQuery({sql:"SELECT a.availability,e.sequence,e.idempotency_key,e.payload_json FROM skill_availability_actions a JOIN events e ON e.id=a.event_id WHERE a.entry_id=? ORDER BY e.sequence",args:[installed.entryId]});expect(actions.map((row:any)=>row.availability)).toEqual(["disabled","enabled","disabled","enabled"]);expect(new Set(actions.map((row:any)=>row.idempotency_key)).size).toBe(4);expect(actions.every((row:any,index)=>index===0||Number(row.sequence)>Number((actions[index-1] as any).sequence))).toBe(true);expect(actions.map((row:any)=>JSON.parse(String(row.payload_json)).expectedPreviousActionSequence)).toEqual([null,Number((actions[0] as any).sequence),Number((actions[1] as any).sequence),Number((actions[2] as any).sequence)]);
  const priorSequence=Number((actions.at(-1) as any).sequence),basePayload={entryId:installed.entryId,versionId:installed.versionId,digest:installed.digest,reason:"Concurrent lifecycle race",expectedAvailability:"enabled" as const,expectedPreviousActionSequence:priorSequence};const raced=await Promise.allSettled([s.storage.appendEvents([{sessionId:session.sessionId,branchId:session.branchId,type:"SkillAvailabilityChanged",producer:"client",idempotencyKey:`race-disable:${installed.versionId}`,payload:{...basePayload,availability:"disabled"}}]),s.storage.appendEvents([{sessionId:session.sessionId,branchId:session.branchId,type:"SkillAvailabilityChanged",producer:"client",idempotencyKey:`race-remove:${installed.versionId}`,payload:{...basePayload,availability:"removed"}}])]);expect(raced.map(result=>result.status).sort()).toEqual(["fulfilled","rejected"]);const winner=raced.findIndex(result=>result.status==="fulfilled")===0?"disabled":"removed";expect((await s.skillManagement.get(session.sessionId,session.branchId,installed.entryId)).availability).toBe(winner);expect(await contextHas()).toBe(false);
 });

 test("exposed candidates invoke only on the exact allocated branch and record post-exposure retests",async()=>{const {supervisor:s}=await open();const session=await s.createSession({workspaceId:"w"});const evidence=await s.appendMessage(session.sessionId,session.branchId,"user","candidate evidence");let proposal=await s.harness.propose(session.sessionId,session.branchId,{trigger:"candidate",predictedEffect:"candidate",evidenceEventIds:[evidence.id],evaluation:{kind:"objective",name:"test",metric:"ok",target:true},edits:[{operation:"create",kind:"skill",scope:"workspace",name:"candidate-only",content:{kind:"skill",description:"candidate",source:"export default () => ({ok:true});",permissions:[],runtime:"bun",tests:[{name:"ok",input:null,expected:{ok:true}}]}}]});proposal=await s.harness.validate(session.sessionId,session.branchId,proposal.proposalId);proposal=await s.harness.activate(session.sessionId,session.branchId,proposal.proposalId);const candidate=(await s.harness.list({kind:"skill"})).find(item=>item.name==="candidate-only")!;await expect(s.skills.invoke(session.sessionId,session.branchId,candidate.entryId,null,{versionId:candidate.current.versionId})).rejects.toMatchObject({code:"CANDIDATE_NOT_EXPOSED"});const allocation=await s.harness.allocate(session.sessionId,session.branchId,proposal.proposalId);await s.harness.expose(session.sessionId,session.branchId,proposal.proposalId,allocation.allocationId);expect(await s.skills.invoke(session.sessionId,session.branchId,"candidate-only",null,{versionId:candidate.current.versionId})).toMatchObject({outcome:"succeeded",versionId:candidate.current.versionId});const history=await s.storage.loadEvents(session.sessionId,{branchId:session.branchId});const forkCursor=history.at(-1)!.cursor;const otherBranch="other-candidate-branch";await s.storage.appendEvents([{sessionId:session.sessionId,branchId:otherBranch,type:"BranchCreated",producer:"client",idempotencyKey:"other-candidate-branch",payload:{branchId:otherBranch,parentBranchId:session.branchId,forkCursor}}]);await expect(s.skills.invoke(session.sessionId,otherBranch,candidate.entryId,null,{versionId:candidate.current.versionId})).rejects.toMatchObject({code:"CANDIDATE_NOT_EXPOSED"});});

 test("protocol client exposes preview/install/list/show/test and lifecycle commands",async()=>{const {supervisor:s,temp}=await open();const session=await s.createSession({workspaceId:"w"});const directory=await bundle(temp,"protocol-triple");const protocol=new ProtocolServer(s);const server=protocol.listen(0);const client=new AgentClient(`http://${server.hostname}:${server.port}`);try{const preview=await client.previewSkillImport(session.sessionId,session.branchId,directory);const installed=await client.installSkill(session.sessionId,session.branchId,{directory,scope:"profile",confirmationDigest:preview.confirmationDigest,installedBy:"protocol-owner"});expect((await client.listSkills(session.sessionId,session.branchId)).map(item=>item.name)).toContain("protocol-triple");expect(await client.getSkill(session.sessionId,session.branchId,"protocol-triple")).toMatchObject({versionId:installed.versionId,source:"profile"});expect(await client.testSkill(session.sessionId,session.branchId,"protocol-triple")).toMatchObject({outcome:"succeeded",failed:0});expect(await client.disableSkill(session.sessionId,session.branchId,"protocol-triple")).toMatchObject({availability:"disabled"});expect(await client.enableSkill(session.sessionId,session.branchId,"protocol-triple")).toMatchObject({availability:"enabled",versionId:installed.versionId});}finally{protocol.stop();}});

 test("rejects invalid skill names before proposal history and quarantines retained invalid harness rows",async()=>{
  const {supervisor:s}=await open();const session=await s.createSession({workspaceId:"w"});const before=(await s.storage.readonlyQuery({sql:"SELECT count(*) AS count FROM refinement_proposals",args:[]}))[0] as any;
  await expect(s.harness.propose(session.sessionId,session.branchId,{trigger:"invalid",predictedEffect:"must reject",authority:"user",evaluation:{kind:"objective",name:"test",metric:"ok",target:true},edits:[{operation:"create",kind:"skill",scope:"workspace",name:"Invalid Skill Name",content:{kind:"skill",description:"invalid legacy name",source:"export default () => ({ok:true});",permissions:[],runtime:"bun",tests:[{name:"ok",input:null,expected:{ok:true}}]}}]})).rejects.toThrow(/lower-kebab/);const after=(await s.storage.readonlyQuery({sql:"SELECT count(*) AS count FROM refinement_proposals",args:[]}))[0] as any;expect(Number(after.count)).toBe(Number(before.count));
  const entryId="entry-legacy-invalid-name",versionId="version-legacy-invalid-name";await s.storage.appendEvents([{sessionId:session.sessionId,branchId:session.branchId,type:"HarnessVersionCreated",producer:"supervisor",idempotencyKey:"legacy-invalid-skill-fixture",payload:{entryId,versionId,version:1,kind:"skill",scope:"workspace",scopeKey:"w",name:"Legacy Invalid Name",content:{kind:"skill",description:"retained invalid fixture",source:"export default () => ({ok:true});",permissions:[],runtime:"bun",tests:[{name:"ok",input:null,expected:{ok:true}}]},tags:[],confidence:1,status:"active",evidenceEventIds:[],conflictEntryIds:[],createdBy:"legacy-import",lastConfirmedAt:"2026-08-06T00:00:00.000Z"}}]);
  expect((await s.skillManagement.list(session.sessionId,session.branchId)).some(item=>item.entryId===entryId)).toBe(false);const retained=(await s.skillManagement.list(session.sessionId,session.branchId,{includeUnavailable:true})).find(item=>item.entryId===entryId);expect(retained).toMatchObject({name:"Legacy Invalid Name",availability:"disabled",legacy:true});expect(retained?.description).toMatch(/quarantined/);const context=await s.contexts.materialize(session.sessionId,session.branchId);expect((context.context as any).harness.skills.some((item:any)=>item.entryId===entryId)).toBe(false);
  expect((await s.skillManagement.get(session.sessionId,session.branchId,entryId)).legacy).toBe(true);await expect(s.skillManagement.enable(session.sessionId,session.branchId,entryId)).rejects.toThrow(/quarantined/);expect((await s.skillManagement.remove(session.sessionId,session.branchId,entryId)).availability).toBe("removed");expect((await s.skillManagement.list(session.sessionId,session.branchId,{includeUnavailable:true})).find(item=>item.entryId===entryId)).toMatchObject({availability:"removed",legacy:true});expect((await s.harness.history(entryId))).toHaveLength(1);
 });

 test("agent skill creation is a constrained skill_creation Refiner review",async()=>{const {supervisor:s}=await open();const session=await s.createSession({workspaceId:"w"});const review=await s.skillManagement.propose(session.sessionId,session.branchId,"Create one reusable formatting skill","workspace");expect(review).toMatchObject({mode:"skill_creation",requestedScope:"workspace",allowedKinds:["skill"]});const event=(await s.storage.loadEvents(session.sessionId,{branchId:session.branchId})).find(item=>item.type==="RefinementReviewRequested")!;expect(event.payload).toMatchObject({mode:"skill_creation",allowedKinds:["skill"],triggerKind:"skill_creation"});});
});
